### PR TITLE
Fix build error on older compilers

### PR DESCRIPTION
**Pull request by tonyhutter**
Fix a build error GCC 4.9.3 (and possibly other versions):
```
    command.hpp: In constructor 'command_t::command_t()':
    command.hpp:16:17: error: array used as initializer
        command_t() { }
```
Closes: #9

### CODE REVIEW

**Comment by tonyhutter** [comment]
@bnicolae yep it builds with 4.9.3 with this fix.  I just added your change in my latest push.
